# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: self-hosted
    steps:
    - name: Check out code
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: 1.20
    
    - name: Build
      run: go build -v -o TravelleRBackend ./...
    
    - name: Deploy
      run: |
        chmod +x ~/hostedProjects/TravelleR/scripts/stop-travelleR.sh
        chmod +x ~/hostedProjects/TravelleR/scripts/start-travelleR.sh
        ~/hostedProjects/TravelleR/scripts/stop-travelleR.sh
        mv TravelleRBackend ~/hostedProjects/TravelleR/
        ~/hostedProjects/TravelleR/scripts/start-travelleR.sh

